workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: python:alpine3.19
# before_script:
#   - apt-get update -qy
#   - apt-get install -y python3-pip

build-job:
  stage: build
  script:
    - pip install -r requirements.txt

test-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest 

build-client:
  stage: build
  image: public.ecr.aws/docker/library/node:lts
  script:
    - npm install
    - npm run build
    
test-client-job:
  stage: test
  image: public.ecr.aws/docker/library/node:lts
  script:
    - npm install
    - npm run test
