workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: public.ecr.aws/ubuntu/ubuntu:22.04
before_script:
  - apt-get update -qy
  - apt-get install -y python3-pip

build-job:
  stage: build
  script:
    - pip3 install -r requirements.txt

test-job:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - python3 -m pytest 

build-client:
  stage: build
  image: public.ecr.aws/docker/library/node:lts
  script:
    - npm install
    - npm run build
    
test-client-job:
  stage: test
  image: public.ecr.aws/docker/library/node:lts
  script:
    - npm install
    - npm run test
